/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/zeldas_moon/scene.gltf --transform 
Files: public/zeldas_moon/scene.gltf [5.07KB] > scene-transformed.glb [1.51MB] (-29683%)
Author: Uliszs.3d (https://sketchfab.com/uliszs.3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/zeldas-moon-79b426f98d96419b9c7974ca284995d5
Title: zelda's moon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.M_ROCA__FINAL} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
